[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; ============================================================
; PARTICAO: huge_app = 3MB para app (era 1.3MB no default)
; ============================================================
board_build.partitions = huge_app.csv

build_flags = 
    -Os
    -ffunction-sections
    -fdata-sections
    -fmerge-all-constants
    -fno-exceptions
    -fno-rtti
    -Wl,--gc-sections
    -Wl,-z,muldefs
    -DCONFIG_ESP_WIFI_80211_TX_SUPPORT=1
    -DBOARD_HAS_PSRAM

lib_deps =
    adafruit/Adafruit SSD1306 @ ^2.5.7
    adafruit/Adafruit GFX Library @ ^1.11.9
    nrf24/RF24 @ ^1.4.7
    bblanchon/ArduinoJson @ ^6.21.0
