[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

board_build.partitions = huge_app.csv

build_flags = 
    -Os
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections
    ; === BYPASS: -zmuldefs permite sobrescrever ieee80211_raw_frame_sanity_check ===
    ; No Arduino-ESP32 o --wrap NAO funciona em lib pre-compilada.
    ; Definimos a funcao diretamente no wifi_bypass.cpp com -zmuldefs.
    -Wl,-z,muldefs
    -DCONFIG_ESP_WIFI_80211_TX_SUPPORT=1

lib_deps =
    adafruit/Adafruit SSD1306 @ ^2.5.7
    adafruit/Adafruit GFX Library @ ^1.11.9
    nrf24/RF24 @ ^1.4.7
